### ISSUE TITLE
Missing symbol `__Z23aCountedObjectAllocatorv`

### ISSUE THREAD

**Issue by ansonyuu** [jintonic/gears#16]
Wondering if anyone is also running into this or if there are any pre-installs that I need to make this work. On the M2 Mac

```
dyld[18935]: Symbol not found: __Z23aCountedObjectAllocatorv
  Referenced from: <26054801-0C69-32CD-888F-4AB0274A1E65> /Users/ansonyu/Documents/x/gears/new/gears
  Expected in:     <no uuid> unknown
[1]    18935 abort      ./gears
```

**Comment by jintonic** [comment]
More background information may help us identify the problem. Google CountedObjectAllocator doesn't give anything meaningful to me. What's the version of Geant4 that you are using? Did you enable Qt? Did you run `brew upgrade` after you compiled Geant4? I just tried gears with Geant4.11.1.3 with Qt enabled yesterday on my M2, everything was fine. The reason for that reinstallation was because brew changed location of some dependents for Geant4.

**Comment by ansonyuu** [comment]
Just resolved it!

1. Cleared my build directory within `/gears`
2. Ran cmake again in terminal with source and build location flags `cmake -S  ./ -B ./build `
3. Running `cd build` and `make`
4. Running `./gears`
